os:
  - linux
sudo: false
language: python
services:
- postgresql
python:
- 3.7.4
env:
- DJANGO=2.2.5 DB=postgres
install:
- pip install -r requirements.txt
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - psql -c "CREATE USER project_medical_user WITH PASSWORD 'password';" -U postgres
  - psql -c 'ALTER USER project_medical_user CREATEDB;'  -U postgres
  - cd ./client/project_medical_app
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
  - cd ./../..
script:
  - python manage.py test
  - cd ./client/project_medical_app
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache