name: project_medical_app
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluro: ^1.5.1
  theme_provider: ^0.3.1
  timeago: ^2.0.21
  material_design_icons_flutter: ^3.2.4595 
  provider: ^3.1.0+1
  flutter_spinkit: ^4.0.0
  dio: ^3.0.4
  cached_network_image: ^1.1.1
  flutter_markdown: ^0.3.0
  flutter_map: ^0.7.3
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/logo.png"
  
flutter_native_splash:
  image: "assets/search.png"
  color: "ffffff"

flutter:
  uses-material-design: true

  assets:
   - assets/logo.png
   - assets/search-page.png