name: project_medical_app
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluro: ^1.5.1
  theme_provider: ^0.3.1
  timeago: ^2.0.21
  material_design_icons_flutter: ^3.2.4595 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/logo.png