# Generated by Django 2.2.5 on 2019-11-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20191109_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggest', to='search.Disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggest', to='search.Symptom')),
            ],
            options={
                'unique_together': {('symptom', 'disease')},
            },
        ),
        migrations.DeleteModel(
            name='Shows',
        ),
    ]
