# Generated by Django 2.2.5 on 2019-11-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20191109_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='search.Medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='search.Pharmacy')),
            ],
            options={
                'unique_together': {('pharmacy', 'medicine')},
            },
        ),
        migrations.DeleteModel(
            name='Sells',
        ),
    ]
